### ISSUE TITLE
Permission denied on mounting BikeGAN to local machine

### ISSUE THREAD

**Issue by joleek** [twak/bikegan#1]
I'm getting into a strange permission issue that could very well be a problem with my setup, but I'm sort of out of ideas on what to do.

I'm trying to run BikeGAN using `nvidia-docker2`. The installation went perfectly, no problems with running basic tests with it either. Now, with working directory, `[home]/bikegan-temp`, if I try to run:

`> docker run --runtime=nvidia -v $(pwd)/input:/home/user/bikegan/input -v $(pwd)/output:/home/user/bikegan/output -it --rm twak/bikegan`

That gives the following error:
`docker: Error response from daemon: error while creating mount source path '[home]/bikegan-temp/input': mkdir [home]/bikegan-temp/input: permission denied.`

Okay, what if I try to `mkdir input` and `mkdir output` myself to `[home]/bikegan-temp`, and try to rerun the command?

```
> docker run --runtime=nvidia -v $(pwd)/input:/home/user/bikegan/input -v $(pwd)/output:/home/user/bikegan/output -it --rm twak/bikegan
Loading model bicycle_gan...
---------- Networks initialized -------------
initialization method [xavier]
/home/user/bikegan/models/networks.py:27: UserWarning: nn.init.xavier_normal is now deprecated in favor of nn.init.xavier_normal_.
  init.xavier_normal(m.weight.data, gain=1.0)
initialization method [xavier]
/home/user/bikegan/models/networks.py:29: UserWarning: nn.init.xavier_normal is now deprecated in favor of nn.init.xavier_normal_.
  init.xavier_normal(m.weight.data, gain=1.0)
-----------------------------------------------
model [BiCycleGANModel] was created
Loading model bicycle_gan...
Unhandled exception in thread started by <bound method Interactive.go of <__main__.Interactive object at 0x7f386059feb8>>
Traceback (most recent call last):
  File "/home/user/bikegan/test_interactive.py", line 331, in go
    os.makedirs(input_folder + "val", exist_ok=True)
  File "/home/user/miniconda/envs/py36/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/user/miniconda/envs/py36/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: './input/door textures'
---------- Networks initialized -------------
initialization method [xavier]
initialization method [xavier]
-----------------------------------------------
```
This error prints out ~10 times, each time with a different thing that has permission denied:
```
PermissionError: [Errno 13] Permission denied: './input/roof greebles'
PermissionError: [Errno 13] Permission denied: './input/roof textures'
PermissionError: [Errno 13] Permission denied: './input/pane labels'
PermissionError: [Errno 13] Permission denied: './input/pane textures'
PermissionError: [Errno 13] Permission denied: './input/facade labels'
PermissionError: [Errno 13] Permission denied: './input/facade textures'
PermissionError: [Errno 13] Permission denied: './input/facade greebles'
PermissionError: [Errno 13] Permission denied: './input/facade super'
PermissionError: [Errno 13] Permission denied: './input/roof super'
```

My system:
Ubuntu 14.04.5 LTS
I've tried to install and uninstall docker, checked that my system doesn't use Docker Snap, and tried most things that the internet has told me. Any other ideas?

**Comment by joleek** [comment]
Got this to work by removing `$(pwd)` from the command, `cd`-ing to my temporary directory, and running the following:

`> docker run --runtime=nvidia -v input:/home/user/bikegan/input -v output:/home/user/bikegan/output -it --rm twak/bikegan`

Not exactly sure why that works, but maybe some parts of the absolute path cannot be accessed by docker due to restrictions of my system. Regardless, it seems the relative path works.
