### ISSUE TITLE
assert(torch.cuda.is_available()) AssertionError

### ISSUE THREAD

**Issue by rickkk856** [twak/bikegan#2]
I'm running `python train.py --dataroot ./datasets/08K_Rplan_Black --name 08K_RPlan_Black --model bicycle_gan  --dataset_mode aligned --which_model_netE resnet_512 --use_dropout --loadSize 512 --fineSize 512 --display_winsize 512` on a python 3.6 env 

nvcc  --version returns:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:54:10_Pacific_Daylight_Time_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.relgpu_drvr455TC455_06.29190527_0
```
and 

print(torch.version.cuda)
print(torch. cuda. is_available())
print(torch. cuda. get_device_name(torch. cuda. current_device()))
returns:

```
10.1
True
GeForce RTX 2060
```

Error logs:
```
CustomDatasetDataLoader
dataset [AlignedDataset] was created
#training images = 800
Loading model bicycle_gan...
---------- Networks initialized -------------
Traceback (most recent call last):
  File "train.py", line 26, in <module>
    model = create_model(opt)
  File "C:\Users\Pichau\bikegan-master\models\__init__.py", line 10, in create_model
    model.initialize(opt)
  File "C:\Users\Pichau\bikegan-master\models\bicycle_gan_model.py", line 32, in initialize
    self.init_data(opt, use_D=use_D, use_D2=use_D2, use_E=use_E, use_vae=True)
  File "C:\Users\Pichau\bikegan-master\models\base_model.py", line 46, in init_data
    gpu_ids=self.gpu_ids, where_add=self.opt.where_add, upsample=opt.upsample)
  File "C:\Users\Pichau\bikegan-master\models\networks.py", line 128, in define_G
    assert(torch.cuda.is_available())
AssertionError
```

What torch version and cuda version should I use to be able to run the code... 
a requirements.txt for pip would be useful

**Comment by rickkk856** [comment]
Solved the problem using old version of scipy and loading proper pytorch version on a 3.7 py env [see](https://github.com/twak/bikegan/compare/master...rickkk856:patch-1?expand=1)
